# syntax=docker/dockerfile:1.7
ARG DEPS_IMAGE
FROM ${DEPS_IMAGE}

SHELL ["powershell", "-NoLogo", "-NoProfile", "-ExecutionPolicy", "RemoteSigned", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Write-Host '>>> mach build'; \
    Set-Location \"$env:MOZ_DIR\"; \
    ./mach build; \
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }; \
    Write-Host '>>> done'; \
    Write-Host '>>> [diag] manifest file case in dist/bin/browser/components/ after base build:'; \
    $objDir = (Get-ChildItem -Directory obj-*).Name; \
    Get-ChildItem \"$objDir\dist\bin\browser\components\*.manifest\" -ErrorAction SilentlyContinue | ForEach-Object { Write-Host (\"  \" + $_.Name) }

WORKDIR "${MOZ_DIR}"
