# syntax=docker/dockerfile:1.7
FROM ubuntu:24.04

ARG MOZ_REV

ENV DEBIAN_FRONTEND=noninteractive \
    MOZ_DIR=/build/mozilla-unified \
    MOZBUILD_STATE_PATH=/build/mozbuild \
    SCCACHE_DIR=/build/sccache \
    SCCACHE_CACHE_SIZE=5G \
    CARGO_HOME=/root/.cargo \
    RUSTUP_HOME=/root/.rustup \
    PATH=/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Note: These dependencies are not necessarily required as
# mach bootstrap installs a subset of them into the mozbuild state dir.
RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates mercurial rsync patch curl \
        build-essential m4 autoconf2.13 \
        clang-18 clang++-18 lld-18 llvm-18 libclang-18-dev \
        nasm yasm \
        nodejs npm \
        python3 python3-pip python3-dev \
        libgtk-3-dev libdbus-glib-1-dev libpulse-dev libasound2-dev \
        libxt-dev libx11-dev libx11-xcb-dev libxcb1-dev \
        libxext-dev libxrandr-dev libxcomposite-dev \
        libxcursor-dev libxdamage-dev libxfixes-dev \
        libxi-dev libxrender-dev libxtst-dev \
        libxcb-shm0-dev libxcb-render0-dev \
        zip unzip git \
    && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable && \
    curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

RUN cargo binstall -y cbindgen sccache

RUN mkdir -p "$MOZBUILD_STATE_PATH" "$SCCACHE_DIR" && \
    printf '[mach_telemetry]\nis_enabled = false\nis_set_up = true\n' > "$MOZBUILD_STATE_PATH/machrc"

RUN hg clone --stream https://hg.mozilla.org/mozilla-unified "$MOZ_DIR" && \
    hg --cwd "$MOZ_DIR" update -r "$MOZ_REV"

RUN cd "$MOZ_DIR" && ./mach --no-interactive bootstrap --application-choice=browser

RUN printf '%s\n' \
        'ac_add_options --disable-bootstrap' \
        'ac_add_options --enable-application=browser' \
        'ac_add_options --enable-optimize' \
        'ac_add_options --disable-debug' \
        'ac_add_options --without-wasm-sandboxed-libraries' \
        'ac_add_options --with-ccache=sccache' \
        > "$MOZ_DIR/mozconfig"

RUN cd "$MOZ_DIR" && ./mach build && sccache --show-stats

WORKDIR /build
