# syntax=docker/dockerfile:1.7
FROM ubuntu:24.04

ARG MOZ_REV

ENV DEBIAN_FRONTEND=noninteractive \
    MOZ_DIR=/build/mozilla-unified \
    MOZ_OBJ_DIR=/build/mozilla-unified/obj-x86_64-pc-linux-gnu \
    MOZBUILD_STATE_PATH=/build/mozbuild \
    SCCACHE_DIR=/build/sccache \
    SCCACHE_CACHE_SIZE=10G \
    CARGO_HOME=/root/.cargo \
    RUSTUP_HOME=/root/.rustup

RUN apt update && apt install -y \
        ca-certificates mercurial rsync patch curl \
        build-essential m4 autoconf2.13 \
        clang lld llvm libclang-dev \
        nasm yasm \
        nodejs npm \
        python3 python3-pip python3-dev \
        libgtk-3-dev libdbus-glib-1-dev libpulse-dev libasound2-dev \
        libxt-dev libx11-dev libx11-xcb-dev libxcb1-dev \
        libxext-dev libxrandr-dev libxcomposite-dev \
        libxcursor-dev libxdamage-dev libxfixes-dev \
        libxi-dev libxrender-dev libxtst-dev \
        libxcb-shm0-dev libxcb-render0-dev \
        zip unzip git

RUN mkdir -p /etc/environment.d && \
    echo "PATH=\"\$PATH:$CARGO_HOME/bin\"" \
        > /etc/environment.d/10-cargo.conf

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable && \
    curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

RUN set -a && for f in /etc/environment.d/*.conf; do [ -r "$f" ] && . "$f"; done && set +a && \
    cargo binstall -y cbindgen sccache

RUN mkdir -p "$MOZBUILD_STATE_PATH" "$SCCACHE_DIR" && \
    printf '[mach_telemetry]\nis_enabled = false\nis_set_up = true\n' > "$MOZBUILD_STATE_PATH/machrc"

RUN mkdir -p "$MOZ_DIR" && \
    hg clone --stream https://hg.mozilla.org/releases/mozilla-esr140 -r "$MOZ_REV" "$MOZ_DIR"

RUN cd "$MOZ_DIR" && \
    ./mach --no-interactive bootstrap --application-choice=browser

RUN printf '%s\n' \
        'ac_add_options --enable-application=browser' \
        'ac_add_options --enable-optimize' \
        'ac_add_options --disable-debug' \
        'ac_add_options --with-ccache=sccache' \
        > "$MOZ_DIR/mozconfig"

RUN set -a && for f in /etc/environment.d/*.conf; do [ -r "$f" ] && . "$f"; done && set +a && \
    cd "$MOZ_DIR" && ./mach build && sccache --show-stats

WORKDIR /build
