// This file is automatically generated; do not edit.
export type ModuleMap = {
    "resource://gre/modules/BerytusAgent.sys.mjs": typeof import("./src/Agent.sys.mts"),
	"resource://gre/modules/BerytusChildProxyUtils.sys.mjs": typeof import("./src/ChildProxyUtils.sys.mts"),
	"resource://gre/modules/BerytusLiaison.sys.mjs": typeof import("./src/Liaison.sys.mts"),
	"resource://gre/modules/BerytusNativeManager.sys.mjs": typeof import("./src/NativeManager.sys.mts"),
	"resource://gre/modules/BerytusParentUtils.sys.mjs": typeof import("./src/ParentUtils.sys.mts"),
	"resource://gre/modules/BerytusPromptService.sys.mjs": typeof import("./src/PromptService.sys.mts"),
	"resource://gre/modules/BerytusPromptServiceChildProxy.sys.mjs": typeof import("./src/PromptServiceChildProxy.sys.mts"),
	"resource://gre/modules/BerytusRequestHandler.sys.mjs": typeof import("./src/RequestHandler.sys.mts"),
	"resource://gre/modules/XPCOMUtils.sys.mjs": typeof import("./build/paths/types/gre/modules/XPCOMUtils.d.ts")
}